##############################################################################
### BOOKS ###### BOOKS ###### BOOKS ###### BOOKS ###### BOOKS ###### BOOKS ###
##############################################################################

### BOOKS ### Index
GET http://localhost:3000/books.json

### BOOKS ### Get Songs
GET http://localhost:3000/booksongs/book/Bikg274Y4Q0C.json

### BOOKS ### Show
GET http://localhost:3000/books/1.json

### BOOKS ### Create
POST http://localhost:3000/books.json 
Content-Type: application/json

{
    "google_book_extension": "GZAoAQAAIAAJ"
}

### BOOKS ### Update
PATCH http://localhost:3000/books/3.json 
Content-Type: application/json

{
    "summary": "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for....When House Atreides is betrayed, the destruction of Paul's family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad'Dib, he will bring to fruition humankind's most ancient and unattainable dream."
}

### BOOKS ### Delete
DELETE http://localhost:3000/books/5.json 
Content-Type: application/json

##############################################################################
### SONGS ###### SONGS ###### SONGS ###### SONGS ###### SONGS ###### SONGS ###
##############################################################################

### SONGS ### Index
GET http://localhost:3000/songs.json

### SONGS ### Show
GET http://localhost:3000/songs/id/wtHra9tFISY.json

### SONGS ### Create
POST http://localhost:3000/songs.json 
Content-Type: application/json

# {
#     "url": "https://www.youtube.com/watch?v=Sc8RTc6vKPE",
#     "title": "Dream of Arrakis",
#     "artist": "Hans Zimmer",
#     "album": "Dune (Original Motion Picture Soundtrack)",
#     "genre": "Movie Score",
#     "year": "2021"
# }

{
    "url": "https://www.youtube.com/watch?v=BdtiYwSP9ko"
}

### SONGS ### Update
PATCH http://localhost:3000/songs/id/11.json 
Content-Type: application/json

{
    "year": "2021"
}

### SONGS ### Delete
DELETE http://localhost:3000/songs/id/7.json 
Content-Type: application/json


####################################################################
### BOOKSONGS ###### BOOKSONGS ###### BOOKSONGS ###### BOOKSONGS ###
####################################################################

### BOOKSONGS ### Index
GET http://localhost:3000/book_songs.json

### BOOKSONGS ### Show
GET http://localhost:3000/book_songs/1.json

### BOOKSONGS ### Create
POST http://localhost:3000/book_songs.json 
Content-Type: application/json

{
    "google_book_extension": "e_9MDwAAQBAJ",
    "YT_extension": "4SUGPyZDmVI"
}

### SONGS ### Delete
DELETE http://localhost:3000/book_songs/6.json 
Content-Type: application/json

############################################################################
### OPENLIB-API ###### OPENLIB-API ###### OPENLIB-API ###### OPENLIB-API ###
############################################################################

GET https://openlibrary.org/api/books?bibkeys=ISBN:0451526538

###########################################################################
### GOOGLE-BOOKS-API ###### GOOGLE-BOOKS-API ###### GOOGLE-BOOKS-API ######
###########################################################################


https://www.googleapis.com/books/v1/volumes?q=intitle=hobbit

###
GET http://localhost:3000/query?id=wtHra9tFISY
###
GET http://localhost:3000/songs/search?id=wtHra9tFISY

###
GET http://localhost:3000/songs/search?q=harry%20potter

###
GET https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=surfing&key= Rails.application.credentials.yt_data_api_key HTTP/1.1
